name: Python Tests

on: [push, pull_request]  # Runs on every push or PR

jobs:
  test:
    runs-on: ubuntu-latest  # Use a GitHub-hosted Linux server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Get repo code

      - name: Set up Python
        uses: actions/setup-python@v4  # Install latest Python
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Install pytest globally

      - name: Run tests
        run: pytest test_script.py  # Execute tests
