name: Python Tests

on: [push, pull_request]  # Runs when code is pushed or a PR is created

jobs:
  test:
    runs-on: ubuntu-latest  # Use a GitHub-hosted Linux server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Get repo code

      - name: Set up Docker
        run: docker run --rm python:3.12 bash -c "python --version"  # Test Docker with Python

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pytest

      - name: Run tests
        run: pytest test_script.py  # Running tests
