name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Debug - Show Python Version & Path
        run: |
          which python
          python --version
          which pip
          pip --version

      - name: Install dependencies
        run: |
          python -m ensurepip --default-pip
          python -m pip install --upgrade pip
          pip install pytest

      - name: Debug - Check Files
        run: ls -R

      - name: Run tests
        run: python -m pytest test_script.py || exit 1
